### ISSUE TITLE
Make integration tests for QA

### ISSUE THREAD

**Issue by okdistribute** [dat-land/dat-desktop#155]
hey yall 

We need some tests!

Here's an example testing script:
- https://github.com/datproject/dat-desktop/issues/138

#### working with dats
- [x] click 'create new dat' and share a local folder, you should see a new item in the list
- [x] click the link icon and it should copy the dat link to your clipboard
- [x] click the open in finder icon and it should open the folder in Finder.app
- [x] check that clicking cancel on the delete dialog cancels the dialog
- [x] click the delete icon and it should pop up a confirmation dialog to remove it
- [ ] click 'import dat' and see if can downloads dat://f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062
- [ ] the progress bar should correctly show how much progress you have downloaded

Examples:
- [webtorrent](https://github.com/feross/webtorrent-desktop/tree/master/test) uses tape as well as screenshot tests.
- [beaker](https://github.com/beakerbrowser/beaker/tree/master/tests)

**Comment by yoshuawuyts** [comment]
I think using tape for some of our basic state mutations would be good;
having the full range of integration tests might take a bunch of time and
right now is perhaps not the right time for that.

So far non-IO unit tests have been easy to write for our crash service, and
I think that might be great for an initial pass (:
https://github.com/yoshuawuyts/crash-reporter-service/tree/master/tests

I think one of the biggest pieces of untested code right now is the
dat-manager stuff, but I think now that multidrive is supported by dat-node
we can make this trivial / perhaps move out of our tree to something we can
add more tests too.

Does that make sense?

**Comment by karissa** [comment]
As long as the tests catch bugs before users see them, that's what matters !

**Comment by yoshuawuyts** [comment]
I've been scratching my head a lil over this as I'm not too familiar with Selenium and writing integration tests; I think I'd rather implement unit tests for our models first.

@karissa Is this something you're interested in picking up?

**Comment by yoshuawuyts** [comment]
Another approach we could take is by unit-testing UI things through https://github.com/mantoni/choo-test - haven't tried the library but it could perhaps be a lil more robust compared to selenium. Or perhaps we should like do both?

**Comment by martinheidegger** [comment]
Created issue https://github.com/dat-land/dat-desktop/issues/592 for porting the manual list entirely to integration tests. But I guess further issues might be useful too.
