### ISSUE TITLE
Add label and/or tooltip to line actions

### ISSUE THREAD

**Issue by Kriesse** [dat-land/dat-desktop#183]
Current status:

![image](https://cloud.githubusercontent.com/assets/53684/22358232/3cd7d6ec-e3f2-11e6-962c-4010d343c46e.png)

**Comment by yoshuawuyts** [comment]
@Kriesse do you want to add the labels too, or is this feature ready?

**Comment by AtuyL** [comment]
done :)
https://github.com/dat-land/dat-desktop/pull/584
