### ISSUE TITLE
full screen animation looks kinda weird

### ISSUE THREAD

**Issue by maxogden** [dat-land/dat-desktop#214]
on mac when i click full screen it does this during the transition:

![screen shot 2017-02-10 at 11 16 29 am](https://cloud.githubusercontent.com/assets/39759/22840448/71b279d0-ef82-11e6-9918-d15ad8a452aa.png)

not super important but thought I'd log it in case anyone knows a quick fix

**Comment by yoshuawuyts** [comment]
hahaha, oh wow - yea not entirely sure what's going on there. Just for
reference: which MacOS version are you running?

**Comment by yoshuawuyts** [comment]
@kriesse I suspect it might be that the hex code of the electron background is slightly different from our `neutral` color; just spotted it too when resizing

**Comment by yoshuawuyts** [comment]
Looks like it might be a regression of https://github.com/electron/electron/issues/4992

**Comment by yoshuawuyts** [comment]
@Kriesse did you end up reporting this bug to the Electron team?

**Comment by Kriesse** [comment]
@yoshuawuyts no, not yet.

**Comment by dkastl** [comment]
Seems to work in v3.0.0:latest
