### ISSUE TITLE
Can't log in: Login screen disappears after a short flash

### ISSUE THREAD

**Issue by Kriesse** [dat-land/dat-desktop#426]
In branch  `add/user-accounts`: 
When I click on `Log In`, the form shows for a short moment, then disappears and I'm stuck on this screen.

![login-bug](https://user-images.githubusercontent.com/53684/27134006-6ef219aa-5114-11e7-89a1-3c3ea02969ed.gif)

**Comment by dkastl** [comment]
Outdated branch after move to React.
