### ISSUE TITLE
Switch to React

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/dat-desktop#457]
The title says it all but let me explain the issue: I have tried to help with the update from `mircocomponent` to `nanocomponent` and also tried to improve the existing test situation. And while choo is certainly not a bad framework, I have to say that it made getting into dat-desktop harder. Most of the issues that I have found stem from unclear state management and render triggers _(example: the whole list of items gets re-rendered when only the network state changed)_. 

With `choo` I have yet to find a good way on how to do good propagation of updates in child components in order for parent components to trigger an update  _(example: if the hex-icon changes state that the whole row needs to be redrawn)_. The implementation in the nanocomponent feels hacky at best, both [in the child](https://github.com/aks-/dat-desktop/blob/4350edd752bfa41dc21e59d9c50957c5f07f33a6/elements/table-title-field.js#L185-L198) and [in the parent](https://github.com/aks-/dat-desktop/blob/4350edd752bfa41dc21e59d9c50957c5f07f33a6/elements/table-row.js#L188-L190). 

It is possible to work around such issues but seeing as the time working on dat is limited to me I would rather like to focus on improving the desktop than on trying to fix older issues. I have no-one in my local community that I can ask about choo but several people engaged into React development and this is probably true for a lot of other possible contributors. Thus I would like to ask if its okay to send a PR that switches from choo to react.

I am not sure this is needed but here is a short summary of reasons I feel would make it worth to switch:

- Choo doesn't support composite elements, and that makes tracking of changes in subcomponents difficult. (see mentioned above)
- React is more stable (through the sheer amount of users) and comes with [UI debug tools](https://github.com/facebook/react-devtools).
- The choo eventbus system is nice for business logic but problematic when used in wizards like the tutorial. (see https://github.com/dotloom/dat-desktop/commit/81769f0129e22e6f4a222807b4281b9eae3ee054#diff-44c825eae9fb38934a22b1f6a61b8b95)

**Comment by karissa** [comment]
Sounds good to me!

**Comment by yoshuawuyts** [comment]
:+1: sure

**Comment by juliangruber** [comment]
It has started :) https://github.com/datproject/dat-desktop/pull/458

**Comment by juliangruber** [comment]
I've created a GitHub project to track progress: https://github.com/datproject/dat-desktop/projects/1

**Comment by e-e-e** [comment]
This is excellent news. I have plenty of experience with react, so this change will make it much more easier for me to contribute. I am glad that facebook removed the patent from React.

**Comment by simonv3** [comment]
From that project it looks like this is pretty close to done, is that right? It's just a matter of getting all the tests to pass?

**Comment by martinheidegger** [comment]
@simonv3 - There are some issues with adding dats, some build settings are not yet added again. But other than that it should be mostly finished.

**Comment by okdistribute** [comment]
This is done!
