### ISSUE TITLE
Download dat screen

### ISSUE THREAD

**Issue by juliangruber** [dat-land/dat-desktop#460]
https://github.com/datproject/dat-desktop/blob/master/elements/download.js

**Comment by juliangruber** [comment]
let's work on this once the inspect PR landed

**Comment by aks-** [comment]
gonna start working on it pretty soon today, now that inspect PR is landed

**Comment by dkastl** [comment]
@AtuyL, there seems to be an issue with this, but in the project view it's listed in "review":
https://github.com/dat-land/dat-desktop/projects/1

**Comment by martinheidegger** [comment]
The dialog has been added and tested - quite a bit.
