### ISSUE TITLE
Inspect dat screen

### ISSUE THREAD

**Issue by juliangruber** [dat-land/dat-desktop#463]
PR: https://github.com/datproject/dat-desktop/pull/493

**Comment by aks-** [comment]
@juliangruber I have started working on this one...

**Comment by aks-** [comment]
@juliangruber I have little bit of it remaining to complete, I will do it soon and make a pr, at worse by tomorrow morning. Kinda caught up in a lot of work at work :x

**Comment by juliangruber** [comment]
sure! :)

**Comment by juliangruber** [comment]
Every second of your contribution is greatly appreciated!

**Comment by aks-** [comment]
@juliangruber can you please take a look a look at this and let me know if you would want anything changed to address this issue? - https://github.com/datproject/dat-desktop/pull/493
