### ISSUE TITLE
Redux or Mobx

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/dat-desktop#494]
In the #458 rewrite of Dat-desktop from `choo` to `react`, [`Redux`](https://redux.js.org/) is used for state management. Sadly I have not much experience with `Redux` but as I understand i know that there is always the issue with "what component should be redraw on which property" sort of thing. [`mobx`](https://mobx.js.org/) uses a similar approach to Meteor that I found genuinely awesome that might make our work a lot easier.

I smushed together a simple example to illustrate how this could come in handy _(you can see [a live version here](https://jsfiddle.net/mastakaneda/s7zqmj8L/))_:

```javascript
var dats = mobx.observable([
  {name: 'funny', peers: 0},
  {name: 'bunny', peers: 0}
])
var state = mobx.observable({
  dats,
  connections: 0
})

console.log('Start')

mobx.autorun(function listDats () {
  // Note: I intentionally used 'dats' directly here to indicate that either reference can be used!
  console.log(`${dats.length} dats:`)
  dats.forEach(entry => {
    console.log(` - ${entry.name}`)
  })
})

mobx.autorun(function appInfo () {
  console.log(`Dat Display: ${state.dats.length} dats ~ ${state.connections} live connections`)
})

console.log('-> changing peers')
state.dats[0].peers = 2 // This will not trigger "listDats" because the title is not used!
console.log('-> rename - same name')
state.dats[0].name = 'funny' // This will not trigger "listDats" because the name stayed same!
console.log('-> rename - different name')
state.dats[0].name = 'pixy' // This will only trigger "listDats" because the name is of one child is used
console.log('-> more connections')
state.connections = 13 // This will only trigger "appInfo" because connections is only used by "appInfo"
console.log('-> Adding to a list')
state.dats.push({name: 'moo', peers: 2}) // This will trigger both as the dat-count is part of both.
```

**Comment by martinheidegger** [comment]
Since we progressed quite far with redux I assume it is going to stay. But this article is interesting https://hackernoon.com/redesigning-redux-b2baee8b8a38

**Comment by e-e-e** [comment]
I have no experience with mobx, but have worked with redux for over a year.
Although it can seem complex to begin with, the concepts are quite simple and powerful once you are familiar with them. Plus - redux devtools are super handy for debugging or just generally seeing how your app is working - https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en.

**Comment by martinheidegger** [comment]
Since the react branch is already mostly ready using redux, I will close this issue
