### ISSUE TITLE
We have a new home!

### ISSUE THREAD

**Issue by juliangruber** [dat-land/dat-desktop#495]
Hey everyone, look at our shiny new home :)

Going forth, dat-land is the place for all dat related projects that aren't officially supported by the datproject itself, but where the user land comes together to collaborate!

In the upcoming days we'll implement a contribution workflow for this repository, which will be an example for upcoming projects making it to this organization as well.

Expect more information soon, but for now, I just wanted to let you know we now have the freedom to make independent contributors full collaborators on dat-desktop!

🎆 🍾 🎉

**Comment by okdistribute** [comment]
We're going to move this back to datproject organization, since that has become the defacto community org and has  more stars/attention!
