### ISSUE TITLE
add non-dom tests

### ISSUE THREAD

**Issue by aks-** [dat-land/dat-desktop#521]
add non-dom tests so that we do not need to restart the whole electron setup from zero, which is pretty time consuming

**Comment by aks-** [comment]
here is branch that i've started working on - https://github.com/dat-land/dat-desktop/tree/add/unit-tests

**Comment by aks-** [comment]
oops, mistakenly closed it

**Comment by dkastl** [comment]
Tests are now in the unit tests folder. Create new issue if necessary.
