### ISSUE TITLE
Counter-productive OS support choices

### ISSUE THREAD

**Issue by medavox** [dat-land/dat-desktop#528]
Given the primary use-case of this project, I strongly recommend you prioritise Windows support above everything.

Supporting an elitist minority walled-garden (Apple appliances) before the most common workstation OS in academic institutions seems an odd choice.

**Comment by karissa** [comment]
Thanks @medavox! It should support Windows -- you're right. It's been a hard road, though, to get p2p networking working well on Windows.

**Comment by karissa** [comment]
Have you tried the command-line application? It has been tested and should work on Windows. https://github.com/datproject/dat/releases/download/v13.10.0/dat-13.10.0-win-x64.zip

**Comment by aadilayub** [comment]
Bumping this. I've been wanting to use dat to share files with friends, but can't since almost everyone uses Windows where I live. What can the community do to make dat accessible on Windows (for non-cli users)?

**Comment by okdistribute** [comment]
Hey @aadilayub thanks for wanting to help! Dat is pretty low resourced at the moment and there is no one who is being paid to maintain the desktop app.

However, everything should work on windows, someone needs to update this repository with the latest versions of hypercore8 and hyperdrive v10 and hyperswarm. You can use github.com/datproject/sdk for a starting place, or do it with the underlying components. cc @zootella

**Comment by aadilayub** [comment]
@okdistribute Thank you for the detailed instructions! I'm pretty unfamiliar with node/dat tooling, but hoping I'll be able to get this done in the coming weeks :pray:

**Comment by okdistribute** [comment]
This might be able to work if you have a bit of time, even without upgrading to the latest dat components!

**Comment by okdistribute** [comment]
OK I got this to work on windows, please see the releases page, PRs & testing helpful and welcome!

**Comment by aadilayub** [comment]
awesome!
