### ISSUE TITLE
Nothing happens when opening on mac os x 10.9.5

### ISSUE THREAD

**Issue by simonv3** [dat-land/dat-desktop#531]
Due to old hardware reasons (and tech-hesitant partners) I have a macbook that is still running on 10.9.5 and when I install `dat-desktop` on it nothing happens. The app icon pops up, but nothing happens, no other windows, etc. I do however get a crash report!

1. Which version of Dat Desktop are you running?
Downloaded 2.0.0 from the download instructions
2. What operating system and processor architecture are you using?
Mac OS X 10.9.5 Intel Core 2 Duo Macbook Pro
3. What did you do?
Download dat-desktop, drag the application into my Applications folder, open it.
4. What did you expect to see?
The dat-desktop
5. What did you see instead?
Nothing
 
Generated .crash file:
[Dat Helper_2018-05-06-171053_My-MacBook-Pro.txt](https://github.com/dat-land/dat-desktop/files/1978242/Dat.Helper_2018-05-06-171053_My-MacBook-Pro.txt)

It's entirely possible that this is because the OS is old on this computer, but I hope not!

**Comment by martinheidegger** [comment]
Electron doesn't support old versions of Mac os: https://electronjs.org/docs/tutorial/support which means we sadly won't be able to provide support for this.
