### ISSUE TITLE
AppImage icon doesn't work in the dash

### ISSUE THREAD

**Issue by simonv3** [dat-land/dat-desktop#532]
This being an issue in dat-desktop and patchwork made me aware that this was probably an electron setting: https://github.com/ssbc/patchwork/issues/693 here. 

If it's the same issue it's a quick fix, I just can't find where the icon is set and I'm willing to put in the PR for it.

Currently looks like this: 
![screenshot from 2018-05-07 10-28-21](https://user-images.githubusercontent.com/485583/39718439-c0853b88-51e2-11e8-8fb5-47d930f8b688.png)

**Comment by dkastl** [comment]
@AtuyL , let's see if this still  is the case in the latest version

**Comment by martinheidegger** [comment]
It seems like the App Icon needs to be set in the main js: 

> Open main.js and add icon: path.join(__dirname, 'assets/icons/png/64x64.png') when instantiating the BrowserWindow. But also var path = require(‘path’) at the top of the main.js.

[Source](https://www.christianengvall.se/electron-app-icons/)

**Comment by martinheidegger** [comment]
I tried to add the image in the BrowserWindow but it didn't have any impact.

**Comment by dkastl** [comment]
Should be fixed with https://github.com/dat-land/dat-desktop/pull/583/commits/63ec89f62065b21d37a38c728971536b85ffcacf
