### ISSUE TITLE
Blank screen after clicking "BACK TO OVERVIEW"

### ISSUE THREAD

**Issue by iosefa** [dat-land/dat-desktop#534]
I cloned the repo and I am able to run `npm install && npm start` to get the application started. However, run into a problem when I click on a dat file to see details. While it takes me to the page showing details just fine, when I click on "BACK TO OVERVIEW", the screen goes completely blank. I've attached a screenshot of both the detail page and the blank page.

<img width="794" alt="dat1" src="https://user-images.githubusercontent.com/24607032/40370237-cab53c1c-5dad-11e8-89eb-6483e6fe0330.png">

<img width="801" alt="dat2" src="https://user-images.githubusercontent.com/24607032/40370252-d4ffb2f6-5dad-11e8-9c96-8470b2aba5df.png">

**Comment by martinheidegger** [comment]
Is there an error in the developer console?

**Comment by iosefa** [comment]
Nope. No errors in the development console

**Comment by iosefa** [comment]
But I do get  `🚨 choo No listeners for dats:loaded`

**Comment by martinheidegger** [comment]
We don't work on the choo branch anymore, please retest this on the react branch.

**Comment by iosefa** [comment]
This was on the master branch. This issue does not persist on the react branch.

**Comment by martinheidegger** [comment]
Okay, I will close this issue as the master branch is not relevant to development anymore.
