### ISSUE TITLE
Replace AppVeyor with Travis for Windows

### ISSUE THREAD

**Issue by dkastl** [dat-land/dat-desktop#558]
Travis started support for Windows, which would allow us to only use Travis CI for all operating systems.

**Comment by martinheidegger** [comment]
#552 Is already working on it. Current state is that travis has problems with secrets. Looking forward to updates in the travis pipeline.

**Comment by dkastl** [comment]
This will probably take longer, so moving the issue to another milestone.

**Comment by okdistribute** [comment]
This still doesn't seem to be building a windows version

**Comment by dkastl** [comment]
Eventually Github Actions would be the better alternative now.
