### ISSUE TITLE
Label of buttons don't set anymore.

### ISSUE THREAD

**Issue by martinheidegger** [dat-land/dat-desktop#586]
In DAT@2 there are labels/overlays shown in DAT desktop for the icons:

<img width="110" alt="DAT@2" src="https://user-images.githubusercontent.com/914122/48668489-0899f600-eb32-11e8-9fab-650e6e966e51.png">

https://github.com/dat-land/dat-desktop/blob/05f81099513698c83713a1fcf25a5b91e303b0d3/elements/table-row.js#L241

https://github.com/dat-land/dat-desktop/blob/05f81099513698c83713a1fcf25a5b91e303b0d3/elements/button.js#L111-L114

in DAT@3 it seems it only shows some key.

<img width="79" alt="DAT@3" src="https://user-images.githubusercontent.com/914122/48668490-0899f600-eb32-11e8-8a47-1167c0f8e7b3.png">

**Comment by AtuyL** [comment]
closed by this PR https://github.com/dat-land/dat-desktop/pull/584
